apiVersion: v1
kind: Service
metadata:
  name: sgd
  labels:
    app: sgd
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: sgd

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sgd
spec:
  selector:
    matchLabels:
      app: sgd 
  serviceName: "sgd"
  replicas: 8 # Number of pods (1 coordinator+ workers) -- NEED TO BE EQUAL TO "NUMBER_REPLICAS"
  template:
    metadata:
      labels:
        app: sgd 
    spec:
      terminationGracePeriodSeconds: 2
      containers:
      - name: worker
        image: aliostux/worker:latest
        resources: # Change this more more or less resources
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "750m"
        volumeMounts: 
        - mountPath: "/data" # persistant storage mount path
          name: data-volume
        ports:
        - containerPort: 50051
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NUMBER_REPLICAS # Number of pods (1 coordinator+ workers) -- NEED TO BE EQUAL TO replicas
          value: "8"
        - name: TRAIN_DATA_PATH # Training file path
          value: "/data/datasets/lyrl2004_vectors_train.dat" 
        - name: TEST_DATA_PATH # Test file path
          value: "/data/datasets/lyrl2004_vectors_test_pt0.dat"
        - name: TEST_DATA_PATH_1 # Test file path
          value: "/data/datasets/lyrl2004_vectors_test_pt1.dat"
        - name: TEST_DATA_PATH_2 # Test file path
          value: "/data/datasets/lyrl2004_vectors_test_pt2.dat"
        - name: TEST_DATA_PATH_3 # Test file path
          value: "/data/datasets/lyrl2004_vectors_test_pt3.dat"
        - name: LABEL_DATA_PATH # labels file path
          value: "/data/datasets/rcv1-v2.topics.qrels"
        - name: LOG_FILE # Log file path
          value: /data/out.txt
        - name: LOG_FOLDER # Folder where the weight vector will be saved at the end
          value: /data
        - name: lr # Learning rate
          value: "1"
        - name: tot_iter # Number of iterations
          value: "1000"
        - name: reg # Regularization rate
          value: "0.1"
        - name: ASNYCH # Asynchronous mode flag
          value: '1'
        - name: val_data_size # Number of samples per class in the validation sets
          value: "2000"
        - name: test_after # Validation frequency
          value: "100"
        - name: proba_sample # Sampling probability for validation set
          value: "0.8"
        - name: batch_size # Training batch size
          value: "32"
      volumes:
      - name: data-volume
        persistentVolumeClaim: #Persistant storage claim name
          claimName: cs449g5-scratch
