apiVersion: v1
kind: Service
metadata:
  name: sgd
  labels:
    app: sgd
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: sgd

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sgd
spec:
  selector:
    matchLabels:
      app: sgd # has to match .spec.template.metadata.labels
  serviceName: "sgd"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        app: sgd # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: worker
        image: worker
        imagePullPolicy: Never
        volumeMounts:
        - mountPath: /test-pd
          name: test-volume
        ports:
        - containerPort: 50051
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NUMBER_REPLICAS
          value: "3"
        - name: DATA_DIR
          value: "/usr/share/datasets/"
        - name: TRAIN_FILE
          value: "lyrl2004_vectors_train.dat"
        - name: LABEL_FILE
          value: "rcv1-v2.topics.qrels"
        - name: TEST_FILE_PATH
          value: ccat_test_data.dat
        - name: TRAIN_FILE_PATH
          value: ccat_train_data.dat
        - name: LOG_FILE
          value: out.txt
      volumes:
      - name: test-volume
        hostPath:
          # directory location on host
          path: /Users/alialami-idrissi/Documents/MA2/systems_for_DS/project/sds_epfl2018/Milestone2/docker
          # this field is optional
          type: Directory

# TODO: ADD LIMITS CPU/MEM